export const TABLE_TENANTS = 'tenants'
export const TABLE_PRODUCTS = 'products'
export const TABLE_PRODUCT_LINKS = 'product_links'
export const TABLE_RSVPS = 'rsvps'
export const TABLE_MESSAGES = 'messages'
