import {
	DEFAULT_BACKGROUND_COLOR,
	DEFAULT_PRIMARY_COLOR,
	DEFAULT_SLATE_COLORS,
	DEFAULT_TEXT_COLOR,
	FREE_BACKGROUND_COLORS,
	FREE_PRIMARY_COLORS,
} from "./colors";

export {
	DEFAULT_PRIMARY_COLOR,
	DEFAULT_TEXT_COLOR,
	DEFAULT_BACKGROUND_COLOR,
	FREE_PRIMARY_COLORS,
	FREE_BACKGROUND_COLORS,
	DEFAULT_SLATE_COLORS,
};

export const DEFAULT_TITLE_FONT = "playfair";
export const DEFAULT_BODY_FONT = "inter";
